### ISSUE TITLE
Exception: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by DevanshChoubey** [brunnurs/valuenet#1]
ERROR!!! HTTP: 400. for request 'what is the avearge price of all five star hotel'
{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developers console",
            "url": "https://console.developers.google.com"
          }
        ]
      }
    ]
  }
}

Exception: 'NoneType' object is not subscriptable

**Comment by brunnurs** [comment]
Hi @DevanshChoubey, the manual inference mode uses Google Entities API for NER (https://cloud.google.com/natural-language/docs/analyzing-entities). You need to organize a valid API key and add it to the google_api_repository.py file. The Google API is free up to a certain amount of requests.

I adapted the README with this information.
