### ISSUE TITLE
what is the accuracy of trained model

### ISSUE THREAD

**Issue by vraxzeztan** [brunnurs/valuenet#5]
how long was the trained model trained for?

**Comment by brunnurs** [comment]
![W B Chart 6_22_2020, 9_43_14 AM](https://user-images.githubusercontent.com/1187124/85261691-d3bbf680-b46c-11ea-9a6f-bb61a8942b89.png)

This are the validation results after each epoch for ValueNet (blue) and ValueNet light (redish). We trained always for 100 epochs, even though the model converged earlier.  We reach max results for e.g. ValueNet light after 69 epochs.
